name: Container Image Build

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
  - cron: '9 2 * * *' # 02:09 yyds
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository_owner }}/envoy

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Login against a Docker registry except on PR
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/toolkit
        path: toolkit
    
    - name: setup nushell
      uses: hustcer/setup-nu@v3
      with:
        check-latest: true
    - name: fetch latest envoy version
      shell: nu {0}
      id: latest-versions
      run: |
        use ${{ github.workspace }}/toolkit/nushell/scripts *

        [
            [envoyproxy/envoy ENVOY_VERSION]
        ] | each {|it|
            $it.0 | github-action latest-version | git semver | $"($in.major).($in.minor)" | do {
                $"LATEST_TAG=v($in)-latest" | save -a $env.GITHUB_ENV
                $in
            } | $"($it.1)=($in)"
        } | str join "\n"
        | github-action multi-line LATEST_VERSIONS
        | save -a $env.GITHUB_OUTPUT

    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # Build and push Docker image with Buildx (don't push on PR)
    # https://github.com/docker/build-push-action
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Containerfile
        provenance: false
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_TAG }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ steps.latest-versions.outputs.LATEST_VERSIONS }}